export const FETCH_COMPLAINTS = 'FETCH_COMPLAINTS';
export const FETCH_COMPLAINTS_SUCCESS = 'FETCH_COMPLAINTS_SUCCESS';
export const FETCH_COMPLAINTS_FAILED = 'FETCH_COMPLAINTS_FAILED';

export const CREATE_COMPLAINTS = 'CREATE_COMPLAINTS';

export const TOGGLE_ISAUTHENTICATED = 'TOGGLE_ISAUTHENTICATED';
export const CHANGE_AUTHENTICATION = 'CHANGE_AUTHENTICATION';

export const ADD_COMPLAINT = 'ADD_COMPLAINT';
export const ADD_COMPLAINT_SUCCESS = 'ADD_COMPLAINT_SUCCESS';
export const ADD_COMPLAINT_FAILED = 'ADD_COMPLAINT_FAILED';

export const DELETE_COMPLAINT = 'DELETE_COMPLAINT';
export const DELETE_COMPLAINT_SUCCESS = 'DELETE_COMPLAINT_SUCCESS';
export const DELETE_COMPLAINT_FAILED = 'DELETE_COMPLAINT_FAILED';

export const EDIT_COMPLAINT = 'EDIT_COMPLAINT';
export const EDIT_COMPLAINT_SUCCESS = 'EDIT_COMPLAINT_SUCCESS';
export const EDIT_COMPLAINT_FAILED = 'EDIT_COMPLAINT_FAILED';
